spring:
  application:
    name: productservice

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.diego: DEBUG
server:
  port: 8082
opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus 
